### PR TITLE
Feat/item shop item holder

### PR DESCRIPTION
**Pull request by fabiantran5200**
item shop to buy items

### CODE REVIEW

**Comment by josia-santoso** [comment]
Add buy process logic which are player balance reduction when player buy an item, and logical rules if player has insufficient balance or has the item already they cannot buy the item.

**Comment by KlayQi** [comment]
image
The text is displayed even though no items have been bought

**Comment by josia-santoso** [comment]
> image The text is displayed even though no items have been bought

It is like that, just forgot to put the if. I have added it now.

**Review by KlayQi — COMMENTED** [review]
Also if you buy the first item the game crashes and when you buy the right item it brings you to the game selection

**Review by KlayQi — APPROVED** [review]
bug is gone looks all good to me!

**Pull request merged**
